(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode nil)
 '(c-tab-always-indent nil)
 '(column-number-mode t)
 '(company-auto-complete (quote (quote company-explicit-action-p)))
 '(compilation-message-face (quote default))
 '(css-indent-offset 2)
 '(cua-mode t nil (cua-base))
 '(delete-selection-mode t)
 '(delete-trailing-lines nil)
 '(diff-hl-flydiff-mode t)
 '(display-battery-mode t)
 '(display-time-mode t)
 '(ecb-options-version "2.40")
 '(erc-auto-query (quote window-noselect) t)
 '(erc-autoaway-mode t t)
 '(erc-away-nickname nil t)
 '(erc-join-buffer (quote window-noselect) t)
 '(erc-modules
   (quote
    (completion list menu scrolltobottom autojoin button dcc fill irccontrols match move-to-prompt netsplit networks noncommands readonly ring stamp spelling track)) t)
 '(erc-nick-notify-mode t)
 '(erc-prompt ">" t)
 '(erc-public-away-p t t)
 '(erc-speedbar-sort-users-type (quote alphabetical) t)
 '(erc-user-full-name "Tomás Solar" t)
 '(exec-path-from-shell-check-startup-files nil)
 '(ffap-require-prefix t)
 '(flycheck-javascript-eslint-executable "node_modules/eslint/bin/eslint.js")
 '(flymake-phpcs-location (quote tempdir))
 '(flymake-phpcs-standard "PSR2")
 '(flyspell-issue-message-flag nil)
 '(flyspell-prog-mode 1 t)
 '(fringe-mode (quote (1 . 1)) nil (fringe))
 '(git-state-modeline-decoration (quote git-state-decoration-small-dot))
 '(global-diff-hl-mode t)
 '(global-hl-line-mode t)
 '(global-subword-mode t)
 '(gtags-auto-update nil t)
 '(haml-backspace-backdents-nesting nil)
 '(haml-indent-offset 4)
 '(helm-ag-fuzzy-match t)
 '(helm-ag-use-agignore t)
 '(helm-ag-use-temp-buffer t)
 '(helm-autoresize-mode t)
 '(helm-mode-fuzzy-match t)
 '(identica-display-success-messages t)
 '(identica-soft-wrap-status t)
 '(ido-enable-flex-matching t)
 '(ido-use-filename-at-point t)
 '(indent-tabs-mode nil)
 '(inf-ruby-prompt-read-only nil)
 '(inhibit-startup-screen t)
 '(ispell-extra-args (quote ("--sug-mode=fast")))
 '(ispell-list-command "--list")
 '(jabber-show-offline-contacts nil)
 '(jabber-show-resources nil)
 '(js-indent-level 2)
 '(js2-auto-indent-p t)
 '(js2-bounce-indent-p t)
 '(js2-cleanup-whitespace t)
 '(js2-enter-indents-newline t)
 '(less-css-compile-at-save t)
 '(magit-auto-revert-mode nil)
 '(magit-diff-use-overlays nil)
 '(magit-last-seen-setup-instructions "1.4.0")
 '(nyan-wavy-trail t)
 '(package-selected-packages
   (quote
    (rspec-mode :erc-nick-notify :erc-hl-nicks vdiff-magit vimish-fold auto-complete yasnippet yaml-mode web-mode web-beautify vcl-mode use-package undo-tree twittering-mode tea-time syslog-mode ssh-config-mode solarized-theme smartparens smart-mode-line-powerline-theme smart-mode-line slim-mode scss-mode sass-mode rvm robe rinari rainbow-mode rainbow-delimiters railscasts-theme projectile-rails popwin php-auto-yasnippets nyan-mode nginx-mode neotree mustard-theme multiple-cursors move-text minimap markdown-mode magit lua-mode jump json-mode js3-mode inf-ruby iedit hl-anything highlight-symbol highlight-parentheses highlight-indentation hide-lines helm-rhythmbox helm-rails helm-projectile helm-ls-git helm-fuzzier helm-emmet helm-company helm-ag helm haml-mode gitignore-mode github-theme git-gutter-fringe+ git-gutter+ git-commit fringe-helper flymake-yaml flymake-shell flymake-sass flymake-ruby flymake-python-pyflakes flymake-phpcs flymake-php flymake-lua flymake-less flymake-json flymake-jslint flymake-jshint flymake-hlint flymake-haml flymake-gjshint flymake-cursor flymake-css flylisp flycheck-tip flycheck-pyflakes flycheck flx-ido flx findr f exec-path-from-shell epl emms-info-mediainfo emms elscreen ecb easy-repeat diff-hl darktooth-theme csv-mode company-web company color-theme-github color-theme coffee-mode bash-completion async aggressive-indent ag ac-emmet)))
 '(password-cache-expiry nil)
 '(php-lineup-cascaded-calls t)
 '(php-mode-coding-style (quote pear))
 '(php-template-compatibility nil)
 '(projectile-require-project-root nil)
 '(rainbow-x-colors-major-mode-list
   (quote
    (emacs-lisp-mode lisp-interaction-mode c-mode c++-mode java-mode lua-mode html-helper-mode php-mode css-mode lisp-mode)))
 '(recentf-mode t)
 '(require-final-newline t)
 '(rspec-use-spring-when-possible nil)
 '(ruby-encoding-map
   (quote
    ((us-ascii)
     (shift-jis . cp932)
     (shift_jis . cp932)
     (japanese-cp932 . cp932)
     (undecided . utf-8))))
 '(safe-local-variable-values
   (quote
    ((encoding . utf-8)
     (less-css-output-directory . "../css")
     (less-css-compile-at-save . t))))
 '(save-place t nil (saveplace))
 '(scroll-conservatively 1)
 '(search-ring-update t)
 '(send-mail-function (quote smtpmail-send-it))
 '(show-paren-mode t)
 '(show-paren-style (quote mixed))
 '(show-trailing-whitespace t)
 '(sml/pre-modes-separator (propertize " " (quote face) (quote sml/modes)))
 '(smtpmail-smtp-server "mail.gnuchile.cl")
 '(smtpmail-smtp-service 25)
 '(tab-always-indent t)
 '(tabbar-separator (quote (0.5)))
 '(text-mode-hook (quote (text-mode-hook-identify)))
 '(tramp-chunksize 5000)
 '(tramp-default-host "localhost")
 '(tramp-default-method "ssh")
 '(transient-mark-mode 1)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(vc-annotate-background nil)
 '(vc-annotate-very-old-color nil)
 '(web-mode-enable-current-column-highlight t)
 '(web-mode-enable-part-face nil)
 '(which-function-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "Inconsolata" :foundry "unknown" :slant normal :weight normal :height 113 :width normal))))
 '(git-commit-summary ((t (:inherit font-lock-constant-face))))
 '(helm-buffer-process ((t (:foreground "yellow"))))
 '(highlight ((t (:background nil))))
 '(iedit-occurrence ((t (:background "gold" :foreground "black"))))
 '(linum ((t (:foreground "dark gray"))))
 '(show-paren-match ((t (:background nil :foreground "gold" :weight bold))))
 '(sp-show-pair-match-face ((t (:inherit show-paren-match :background nil))))
 '(sp-show-pair-mismatch-face ((t (:inherit show-paren-mismatch :background nil :foreground "white"))))
 '(web-mode-inlay-face ((t nil)))
 '(web-mode-part-face ((t nil)))
 '(whitespace-line ((t (:background "gray20")))))
